#!/usr/bin/bash

# User environment
export GOPATH=~/go
export PATH=$PATH:$GOPATH/bin

# User specific aliases and functions
alias godev="cd ~/go/src/github.com/rydrman"

export PATH=~/dotfiles/bin:$PATH

# custom prompt
source ~/dotfiles/bash_prompt

eval $(ssh-agent) > /dev/null

# Key bindings, up/down arrow searches through history
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\eOA": history-search-backward'
bind '"\eOB": history-search-forward'

[[ -s /home/rbottriell/.autojump/etc/profile.d/autojump.sh ]] && source /home/rbottriell/.autojump/etc/profile.d/autojump.sh
